name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main  # غيّر ده لو فرعك مختلف

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # خطوة تسحب الكود من GitHub
      - uses: actions/checkout@v3

      # خطوة تثبيت Flutter SDK
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'  # ممكن تحدد نسخة معينة لو عايز

      # خطوة تنضيف المشروع، تثبيت الحزم، وبناء تطبيق الويب
      - name: Build Flutter Web
        run: |
          flutter clean
          flutter pub get
          flutter build web

      # خطوة نشر المشروع على Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_NEWSAPP_498BA }}"
          channelId: live
          projectId: newsapp-498ba  # غيرها بـ Project ID الخاص بمشروعك على Firebase
